In [2]:
import numpy as np

data = np.random.randn(3, 4)
print(data)

[[-0.16965472  2.22441516 -0.91032593  0.02041841]
 [ 0.16688846  1.14239447  0.71807699  2.16027061]
 [ 0.49556012  1.68919932  1.13222094 -0.54419737]]


In [3]:
import numpy as np

data = np.random.randn(3, 4)
print(data, '\n' )
print(data + data)

[[ 0.79853932  0.02354558  0.98212899  0.08910073]
 [-2.1530119  -0.51521716 -0.08621592  0.78614713]
 [ 0.28167299 -1.16666547  0.33803172 -1.45852361]] 

[[ 1.59707864  0.04709116  1.96425798  0.17820146]
 [-4.3060238  -1.03043432 -0.17243185  1.57229427]
 [ 0.56334598 -2.33333093  0.67606343 -2.91704722]]


In [4]:
import numpy as np

data = np.random.randn(3, 4)
print(data, '\n' )
print(data + data, "\n")
print(data * 10)

[[-1.37730252 -0.09591913 -0.12018241 -0.1187765 ]
 [-2.52576238 -0.56772415  1.51196674 -0.89771059]
 [-0.37766331  0.38435967 -0.11062287 -1.49708683]] 

[[-2.75460504 -0.19183825 -0.24036482 -0.23755299]
 [-5.05152477 -1.13544831  3.02393349 -1.79542119]
 [-0.75532661  0.76871933 -0.22124574 -2.99417366]] 

[[-13.7730252   -0.95919127  -1.2018241   -1.18776496]
 [-25.25762385  -5.67724154  15.11966744  -8.97710594]
 [ -3.77663306   3.84359665  -1.10622868 -14.9708683 ]]


In [5]:
import numpy as np

data = np.random.randn(3, 4)
print(data, '\n' )
print(data + data, "\n")
print(data * 10, '\n')
print(data.shape) #shape checking

[[ 0.13701553 -0.71976672  0.57324129  0.89455212]
 [-0.79457516 -1.05902372 -1.20398801 -1.61773569]
 [-0.39543045 -0.53948114  1.35029867  0.04130144]] 

[[ 0.27403106 -1.43953343  1.14648257  1.78910424]
 [-1.58915032 -2.11804743 -2.40797603 -3.23547138]
 [-0.79086091 -1.07896228  2.70059733  0.08260288]] 

[[  1.37015531  -7.19766716   5.73241286   8.9455212 ]
 [ -7.94575162 -10.59023717 -12.03988013 -16.17735692]
 [ -3.95430453  -5.3948114   13.50298667   0.41301442]] 

(3, 4)


In [6]:
import numpy as np

data = np.random.randn(3, 4)
print(data, '\n' )
print(data + data, "\n")
print(data * 10, '\n')
print(data.shape , '\n')
print(data.dtype , '\n') #datatype

[[ 0.191299   -0.00395168 -0.5376327  -0.09651922]
 [ 0.79247209  1.07959695  2.1309556  -0.77395919]
 [ 1.28086043 -0.40025132 -0.25572661 -0.51421231]] 

[[ 0.382598   -0.00790335 -1.07526539 -0.19303844]
 [ 1.58494419  2.1591939   4.26191121 -1.54791838]
 [ 2.56172086 -0.80050264 -0.51145321 -1.02842462]] 

[[ 1.91299    -0.03951677 -5.37632697 -0.96519222]
 [ 7.92472093 10.79596949 21.30955604 -7.73959189]
 [12.80860429 -4.00251319 -2.55726606 -5.14212308]] 

(3, 4) 

float64 



In [7]:
import numpy as np

data = np.random.randn(3, 4)
print(data, '\n' )
print(data + data, "\n")
print(data * 10, '\n')
print(data.shape , '\n')
print(data.dtype , '\n')
print(data.ndim , '\n') #dimension

[[-0.61695385  0.42092973  1.20863447  2.02318321]
 [ 0.17844243 -0.51779096 -0.17714944 -1.93604795]
 [-0.13781089  0.61158735  1.56987191  0.66641875]] 

[[-1.2339077   0.84185945  2.41726894  4.04636642]
 [ 0.35688485 -1.03558193 -0.35429887 -3.87209591]
 [-0.27562179  1.2231747   3.13974383  1.33283751]] 

[[ -6.1695385    4.20929725  12.08634468  20.2318321 ]
 [  1.78442427  -5.17790965  -1.77149436 -19.36047955]
 [ -1.37810894   6.1158735   15.69871914   6.66418754]] 

(3, 4) 

float64 

2 



In [8]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
print(np.zeros((3,6)), '\n')

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] 



In [10]:
print(np.zeros((2,3,6)), '\n')

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]] 



In [11]:
print(np.empty((3,6)))

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [12]:
arr = np.array([1,2,3,4,5,6])
print(arr.astype(np.float64))

[1. 2. 3. 4. 5. 6.]


In [13]:
arr = np.array([4,2,3,7,5,6], dtype = 'int64')
print(arr* 2 , '\n')

[ 8  4  6 14 10 12] 



In [14]:
arr = np.array([4,2,3,7,5,6], dtype = 'int64')
print(arr*arr , '\n')

[16  4  9 49 25 36] 



In [15]:
arr = np.array([4,2,3,7,5,6], dtype = 'int64')
print(2/arr , '\n')

[0.5        1.         0.66666667 0.28571429 0.4        0.33333333] 



In [16]:
arr = np.array([4,2,3,7,5,6], dtype = 'int64')
print(arr**2 , '\n') #double * means power e.g(2 ki power 2)

[16  4  9 49 25 36] 



In [17]:
arr = np.array([4,2,3,7,5,6], dtype = 'int64')
print(np.sqrt(arr) , '\n') #squar root

[2.         1.41421356 1.73205081 2.64575131 2.23606798 2.44948974] 



In [18]:
arr = np.array([4,2,3,7,5,6], dtype = 'int64')
print(np.exp(arr) , '\n') #exponent

[  54.59815003    7.3890561    20.08553692 1096.63315843  148.4131591
  403.42879349] 



In [19]:
arr = np.array([4,2,3,7,5,6], dtype = 'int64')
print(np.mean(arr) , '\n') #mean

4.5 



In [20]:
arr = np.array([4,2,3,7,5,6], dtype = 'int64')
print(np.sum(arr) , '\n') #sum

27 



In [21]:
arr = np.array([4,2,3,7,5,6], dtype = 'int64')
print(np.cumsum(arr) , '\n') #cumsum

[ 4  6  9 16 21 27] 



In [22]:
arr = np.array([4,2,3,7,5,6], dtype = 'int64')
print(np.sort(arr) , '\n') #sort

[2 3 4 5 6 7] 



In [27]:
arr = np.array([4,2,3,7,5,6], dtype = 'int64')
arr1 = np.array([0,1,8,2,6,5])

print(arr > arr1) 

[ True  True False  True False  True]


In [32]:
arr = np.arange(10)
print(arr)

arr2 = arr[5:8]
print(arr2)

arr[:3]=0
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[5 6 7]
[0 0 0 3 4 5 6 7 8 9]


In [41]:
arrNames = np.array(['abc','xyz', 'ijk','abc'])
arrNums = np.random.randn(4,3)

print(arrNums)
print(arrNames)

print(arrNames == 'abc', '\n')
print(arrNums[arrNames == 'abc'], '\n')
print(arrNums[~(arrNames == 'abc')], '\n')

print(np.unique(arrNames))

[[ 0.50549257  0.46765058  0.06085258]
 [ 2.22551214  0.37936184 -0.26459894]
 [-0.09113692 -0.69435249 -0.30474944]
 [ 0.61673448 -0.68860567 -0.04539   ]]
['abc' 'xyz' 'ijk' 'abc']
[ True False False  True] 

[[ 0.50549257  0.46765058  0.06085258]
 [ 0.61673448 -0.68860567 -0.04539   ]] 

[[ 2.22551214  0.37936184 -0.26459894]
 [-0.09113692 -0.69435249 -0.30474944]] 

['abc' 'ijk' 'xyz']


In [46]:
arr1 = np.random.randn(4)
print(arr1, '\n')

arr2 = np.random.randn(4)
print(arr2, '\n')

print(np.maximum(arr1, arr2) , '\n')
print(np.minimum(arr1, arr2))

[ 1.26796725 -0.39313766  1.11062677  0.05288814] 

[-0.05749401  0.56578195  0.94699689  1.5980297 ] 

[1.26796725 0.56578195 1.11062677 1.5980297 ] 

[-0.05749401 -0.39313766  0.94699689  0.05288814]
